### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ualh** [Ualh/Reddit#3]
# Final Graph

- [ ] one graph with all variables
- [ ] one node for author
- [ ] #4
- [ ] one nodes for every comment (without text)
- [ ] when click on one comment node every variable shall appear (length of comment, sentiment, subreddit, topic, …)
- [ ] #5
- [x] #6
